### ISSUE TITLE
⚡ Release v0.0.0

### ISSUE THREAD

**Issue by in4s** [in4s/teamsy#7]
- [x] ** Update RSR (optional)
- [ ] git checkout main
- [x] git pull
- [x] git checkout -b Release_v0.0.0_#7
- [ ] ** check "NO FILES OF LIBRARIES WERE CHANGED WITHOUT LIB RELEASE" by
    - [ ] git status
    - [ ] git diff --name-status v0.0.0 vendor
- [ ] ** insure updated bemblocks files are committed
- [ ] !!! apply SQL migration, if exists, to all sigmas
- [x] Fix the current version number in files:
    - [x] In README.md
    - [ ] In composer.json
- [x] git add . , git commit -m "⚡ Release v0.0.0 close #7"
- [x] (C*rmr) By process IV Create pull request "⚡ Release v0.0.0 close #7"
------
- [ ] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [ ] click and save https://github.com/in4s/teamsy/releases/new?tag=v0.0.0&target=main
- [ ] Increase the version number in local data.js
- [ ] Remove local branch
- [ ] click and save https://github.com/in4s/teamsy/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v0.0.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [ ] Close milestone with current version name
- [ ] Unpin this issue
